%YAML 1.2
---

name: '128x16-se4_baseline04'
gpu: 1

dataset:
    input: '/media/datadrive01/Chess/lc0/data/t75data/*/'
    train_ratio: 0.90
    num_chunks: 10000000
    allow_less_chunks: true
    train_workers: 12
    test_workers: 8
    input_validation: '/media/datadrive01/Chess/lc0/data/validation_data(t75)/'

training:
    path: '/media/datadrive01/Chess/lc0/lczero-training/showboat_nets'
    num_test_positions: 10000
    batch_size: 1024
    num_batch_splits: 4
    swa: true    #----------------------------------------------------------------------------------------
    swa_output: true
    swa_steps: 20
    swa_max_n: 10
    test_steps: 500
    train_avg_report_steps: 500
    validation_steps: 5000
    total_steps: 100000
    checkpoint_steps: 10000
    renorm: false
    lr_values:
        - 0.2
        - 0.02
        - 0.005
    lr_boundaries:
        - 100000                        # steps until 1st LR drop
        - 130000                        # steps until 2nd LR drop
    warmup_steps: 250
    policy_loss_weight: 1.0             # weight of policy loss, value range: 0-1
    value_loss_weight:  0.6             # weight of value loss, values range: 0-1
    moves_left_loss_weight: 0.1         # weight of moves_left loss, values range: 0-1
    q_ratio: 0.00
    shuffle_size: 500000                # typically 500k or more, but you can get away with alot less
    mask_legal_moves: true              # Filters out illegal moves.    NEEDS BETTER EXPLANATION
    precision: 'single'

model:
    filters: 128                         # Number of filters
    residual_blocks: 16                  # Number of blocks
    se_ratio: 4                          # Squeeze Excite structural network architecture.
    policy: 'convolution'
    value: 'wdl'
    moves_left: 'v1'
#    input_type: 'canonical'
    ##########################################################################################
    ##########################################################################################